org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.caching=true


mod_name=Europa Client
mod_id=europa_client
mod_version=2.0.0
mod_group=dev.neuxs
mod_description=A simple client by Neuxs

mod_license=MIT


cosmic_reach_version=0.4.6
cosmic_reach_dependency=>=0.4.2

cosmic_quilt_version=2.3.2
cosmic_quilt_dependency=*

puzzle_loader_version=3.0.2
puzzle_loader_dependency=*

jigsaw_gradle_version=1.0.8
shadow_gradle_version=8.1.1
cosmic_loom_gradle_version=1.1.1


homepage_link=https://neuxs.dev/
issues_link=https://github.com/Neuxs0/Europa-Client/issues
sources_link=https://github.com/Neuxs0/Europa-Client
