buildscript() {
    repositories {
        maven {
            name "JitPack"
            url "https://jitpack.io"
        }
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        mavenCentral()
        gradlePluginPortal()
        mavenLocal()
    }
    dependencies {
        classpath "org.codeberg.CRModders:cosmic-loom:1.1.1"
        classpath "com.github.johnrengelman:shadow:8.1.1"
        classpath "com.github.PuzzleLoader:jigsaw:$jigsaw_gradle_version"
    }
}

include("base")
include("base:common")
include("base:quilt")
include("base:puzzle")

include("cheat")
include("cheat:common")
include("cheat:quilt")
include("cheat:puzzle")

if (file('bypass').isDirectory()) {
    println "Including optional 'bypass' project."
    include("bypass")
    include("bypass:common")
    include("bypass:quilt")
    include("bypass:puzzle")
} else {
    println "Optional 'bypass' project not found, skipping include."
}


rootProject.name = "EuropaClient"