plugins {
    id "java"
    id "jigsaw"
    id "com.github.johnrengelman.shadow"
}

loom {
    splitEnvironmentSourceSets()
    mods {
        "EuropaClient" {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }
    accessWidenerPath = file("src/main/resources/${id}.manipulator")
}

repositories {
    mavenCentral()
    maven {
        url "https://jitpack.io"
    }
}

dependencies {
    // Cosmic Reach
    cosmicReach("finalforeach:cosmicreach-alpha:${property("cosmic_reach_version")}")

    implementation project(":cheat:common")
}

tasks.named("compileClientJava") {
    source(project(":cheat:common").sourceSets.main.allSource)
}

tasks.named("compileClientJava") {
    source(project(":cheat:common").sourceSets.main.allJava)
}

processResources {
    def resourceTargets = ["puzzle.mod.json"]
    def replaceProperties = [
            mod_version     : project.version,
            mod_group       : project.group,
            mod_description : project.description,
            mod_name        : project.name,
            mod_id          : rootProject.property("id")
    ]

    inputs.properties replaceProperties
    replaceProperties.put("project", project)
    filesMatching(resourceTargets) {
        expand replaceProperties
    }
}

jar {
    archiveFileName.set("${rootProject.name}-puzzle-${project.version}-cheat.jar")

    from(project(":cheat:common").sourceSets.main.resources) {
        exclude 'europa_client.mixins.json'
    }

    from(sourceSets.client.output.resourcesDir)
}

tasks.register("copyMixins", Copy) {
    from(file("../common/src/main/resources/europa_client.mixins.json"))
    into(file("src/client/resources"))
    outputs.dir file("src/client/resources")
}

tasks.named("processClientResources") {
    dependsOn tasks.named("copyMixins")
}

jar.dependsOn(tasks.named("copyMixins"))
